name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PUPPETEER_SKIP_DOWNLOAD: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-lib:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 16 ]

    defaults:
      run:
        working-directory: source/packages/ui-library

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: package-lock.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: |
              echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
              echo ${{ secrets.NPM_TOKEN }}

      - name: Cache node_modules 📦
        uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run installation 👨🏻‍💻
        run: npm ci

      - name: Run build ui-library 🏗
        run: npm run build

      - name: Run publish ui-library 🏗
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Run build for ui-library/react 🏗
        run: npm run build
        working-directory: source/packages/ui-library-react

      - name: Run publish ui-library/react 🏗
        run: npm publish --access public
        working-directory: source/packages/ui-library-react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Run build for ui-library/vue 🏗
        run: npm run build
        working-directory: source/packages/ui-library-vue

      - name: Run publish ui-library/vue 🏗
        run: npm publish --access public
        working-directory: source/packages/ui-library-vue
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
