on:
  push:
    branches:
      - feature/ci-cd-publish-release-tag
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Publish Release to NPM

env:
  PUPPETEER_SKIP_DOWNLOAD: true
  NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

jobs:
  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 16 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node }}
            cache: 'npm'
            cache-dependency-path: package-lock.json

      - name: Cache node_modules 📦
        uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run installation 👨🏻‍💻 & Publish to npm 📦
        run: npm run buildCI
