name: Publish Packages

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    ## if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: package-lock.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: |
          echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
          echo ${{ secrets.NPM_TOKEN }}

      - name: Cache node_modules 📦
        uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run installation 👨🏻‍💻
        run: npm ci
        working-directory: source/packages/ui-library

      - name: Run build ui-library 🏗
        run: npm run build
        working-directory: source/packages/ui-library

      - name: Run publish ui-library 🏗
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Run installation in ui-library/react 👨🏻‍💻
        run: npm ci
        working-directory: source/packages/ui-library-react

      - name: Run build for ui-library/react 🏗
        run: npm run build
        working-directory: source/packages/ui-library-react

      - name: Run publish ui-library/react 🏗
        run: npm publish --access public
        working-directory: source/packages/ui-library-react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Run installation in ui-library/vue 👨🏻‍💻
        run: npm ci
        working-directory: source/packages/ui-library-vue

      - name: Run build for ui-library/vue 🏗
        run: npm run build
        working-directory: source/packages/ui-library-vue

      - name: Run publish ui-library/vue 🏗
        run: npm publish --access public
        working-directory: source/packages/ui-library-vue
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
